version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "127.0.0.1:8080:8080"
    # command: >
    #   poetry run uvicorn app.main:app --host=0.0.0.0 --reload
  backend:
    build:
      context: ./backend
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - type: bind
        source: ./backend/.env
        target: /app/.env
    # command: >
    #   poetry run uvicorn app.main:app --host=0.0.0.0 --reload
