version: "3.8"

services:
  frontend:
    # container_name: frontend
    build:
      context: ./frontend
      # dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    # command: >
    #   poetry run uvicorn app.main:app --host=0.0.0.0 --reload
